### ISSUE TITLE
filter for non-kosha files

### ISSUE THREAD

**Issue by aupasana** [sanskrit-kosha/kosha#10]
Some folders (eg. nanartharatnamala_irugapa/orig ; scripts/ etc) have files that have content that is not the primary kosha content. If the "main" kosha files can be indicated somehow, then it will be easier to integrate with scripts that are trying to process those files.

Some possible implementations:

- Add a metadata file to folders which do not contain kosha files
- Change the extension to files that are the final kosha files
- Add an index file with the names of all the kosha files in the repo

In my case, I am trying to facilitate searching of these kosha files. It will be helpful to automate identification of the relevant files.

If you have a preference for the implementation, I would be happy to send a pull request.

**Comment by drdhaval2785** [comment]
Except scripts and docs folder, all other folders follow this method in the madness for the main content file.

Bookname_Authorname/orig/Bookname.txt

**Comment by aupasana** [comment]
Thanks, that works.
