### ISSUE TITLE
नाममालिका correction

### ISSUE THREAD

**Issue by Harunaga-Isaacson** [sanskrit-kosha/kosha#12]
In 253b नृत्तं गान च कुर्वते is indeed what is printed, apparently. It must I think be a typo for
नृत्तं गानं च कुर्वते .

With many thanks and much appreciation for the wonderful work in digitizing Sanskrit lexicographical texts,

Harunaga Isaacson

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-kosha/kosha/commit/b62d0a1c7bc972934951e02221a9056dd26cd356 closed this. given v0.1.1
