### ISSUE TITLE
Typos in Śāradīyākhyanāmamālā

### ISSUE THREAD

**Issue by Harunaga-Isaacson** [sanskrit-kosha/kosha#17]
1. In the line
मञ्जीरं पादकटकं तुलाकोटिश्च नुपुरम् ।

नुपुरम् , though indeed what is printed, is certainly
a typo for नूपुरम् , as also the metre confirms.

2. There seems to be a subtle fault in encoding in the line
परिभाषणमुपालम्भः शपथ: शपनं शपः ॥ ९९ ॥
Instead of शपथ: it should be शपथः ; there is what appears to
be a Roman colon instead of a Devanagari visarga.

3. The same mistake seems to occur in the line
छेको नागरिक: सुज्ञो वाग्मी व्युत्पन्न एव च ॥ ११६ ॥
where नागरिक: should rather be नागरिकः .

With deep appreciation of the very valuable work,

Harunaga Isaacson

**Comment by Harunaga-Isaacson** [comment]
I now realize that there are quite a few other cases of colon instead of visarga. A search should find them easily.

H.I.

**Comment by drdhaval2785** [comment]
Thank you Prof. Isaacson.

Will work on the errors and make necessary corrections.
