### ISSUE TITLE
Typo in Śivakoṣa of Śivadatta

### ISSUE THREAD

**Issue by Harunaga-Isaacson** [sanskrit-kosha/kosha#22]
The line
पीतपुष्पी तु देवार्हात्रपुसीवारुणिशणे ॥ २९७ ॥
has a typo: it should end -वारुणीशणे ॥

The edition seems to have a rather consistent idiosyncracy;
it prints छ where we should usually, because of internal sandhi,
have च्छ. Thus for instance the plant called मणिच्छिद्रा appears here (in 429a) as मणिछिद्रा. In some cases this affects the metre. I am not sure whether it might be better to 'normalize' the orthography in this regard, rather than to follow the edition.

With many thanks,

Harunaga Isaacson

**Comment by drdhaval2785** [comment]
I incline towards not disturbing the editor choice. I would note this peculiarity in the metadata file. This would caution the user about this peculiarity.
