### ISSUE TITLE
Corrigenda in Dharaṇikośa text

### ISSUE THREAD

**Issue by Harunaga-Isaacson** [sanskrit-kosha/kosha#23]
1. The line 
अलर्को योगितः श्वा स्याच्छ्वेवतार्कपर्णपादपः ॥
has an extra syllable. It should read
अलर्को योगितः श्वा स्याच्छ्वेतार्कपर्णपादपः ॥

2. In the line
कम्बू कुञ्जरशम्बूको कम्बुर्वलयशङ्खयोः ॥
कुञ्जरशम्बूको  should be corrected to कुञ्जरशम्बूकौ .

3. Similarly, in the line
प्रत्युषो प्रभातवसू शैलूषौ बिल्वनर्तकौ ॥
प्रत्युषो  is a mistake for प्रत्युषौ .

4. The line
तारोऽत्युच्चध्वनितरणयोः कीशमुक्ताविशुद्धयो-
should read
तारोऽत्युच्चध्वनितरणयोः कीशमुक्ताविशुद्ध्यो- ,
as also the metre shows.
(Not sure if the conjunct ddhyo will display properly on all systems; in Roman transliteration, the correction consists of ddhayo --> ddhyo.)

5. In the line 
ओऔशब्दौ तु होहौवत्संबुद्धयाह्वानयोः स्मृतौ।
there is again what I suppose is an OCR error, ddhy having been wrongly recognized as ddhay. It should read
ओऔशब्दौ तु होहौवत्संबुद्ध्याह्वानयोः स्मृतौ।

6. In the line
हे है व्यस्तो समस्तौ च हूतौ संबोधने स्मृतौ ॥
व्यस्तो should be corrected to व्यस्तौ .

I conclude that one of the repeated weaknesses of OCR at the moment is occasional mis-recognition of medial au as medial o,
another being difficulty in distinguishing ddhy and ddhay. Not
sure if there may be a way to check for problems of this kind automatically.

With deep appreciation and many thanks,
Harunaga Isaacson

**Comment by drdhaval2785** [comment]
I would say that it is not only the error of OCR. The person who proofread also had a tendency to misread triple / more conjoints. Therefore the OCR error also passed the human scrutiny.

**Comment by Harunaga-Isaacson** [comment]
Yes, no doubt these are difficult for the human eye as well.

**Comment by drdhaval2785** [comment]
I have noticed one more error.
In the line
शङ्गाटकः स्याच्छैवालविशेषे [च] चतुष्पथे ।
the first word is a mistake for
शृङ्गाटकः .
