### ISSUE TITLE
Amarakosha data

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-kosha/kosha#30]
Have received the data of Amarakosha courtesy Prof. Amba Kulkarni.
Need to add this kosha in the present format.
It is the major dictionary missing in this collection.

**Comment by aupasana** [comment]
Please see the links from amara.aupasana.com. This was also based on Prof Kulkarni’s work, but with many corrections made. The updated csv data is on github already.

**Comment by drdhaval2785** [comment]
Ok. Will do so. Thanks

**Comment by drdhaval2785** [comment]
Where can I see the corrected txt file for your work @aupasana ?

**Comment by aupasana** [comment]
https://github.com/aupasana/amara-quiz/tree/master/database

See amara_mula.utf8 for the main text.

**Comment by drdhaval2785** [comment]
Already added.
