### ISSUE TITLE
हलायुधकोशः (अभिधानरत्नमाला) typo

### ISSUE THREAD

**Issue by Harunaga-Isaacson** [sanskrit-kosha/kosha#35]
In 517b

क्म्बुग्रीवेति --->  कम्बुग्रीवेति .

With thanks and much appreciation,

Harunaga Isaacson

**Comment by drdhaval2785** [comment]
Namaste @Harunaga-Isaacson 
Good to see you after a long time. 

I know that it is too much to ask.
But I would love to have pull requests, as you are a regular contributor.
If I have pull requests, I can merge it on mobile also. I can merge your changes even when I am away from my computer.

Kindly have a look at the following video. It is not as difficult as it may seem on first look.
https://youtu.be/rgbCcBNZcdQ
