### ISSUE TITLE
Highlight the results

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-kosha/kosha#36]
A small suggestion that may improve front-end accessibility: it may make it easier for the user if the search-term were to be somehow highlighted in the results. I often find that it takes me time to find the word I'm looking for when there are a large number of results.

**Comment by ujjvlh** [comment]
[इ॒दं](https://github.com/sanskrit-kosha/kosha/pull/37) दृ॑श्यताम्।

**Comment by drdhaval2785** [comment]
Thanks to @ujjvlh this work is now done, and also installed on the website.
