### ISSUE TITLE
ARMH discussion entries

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-kosha/kosha#40]
```
चैत्रादिमासा मधुमाधवौ द्वौ,
ततः परं शुक्रशुची क्रमेण ।
नभोनभस्यौ कथिताविषोर्जौ,
सहःसहस्यौ च तपस्तपस्यौ ॥ ११४ ॥
```
I am not sure what is the parse of the words कथिताविषोर्जौ in this verse?
Can you help in the matter, @Harunaga-Isaacson ?

**Comment by Harunaga-Isaacson** [comment]
Padaccheda:
kathitau, iṣorjau.
iṣorjau is a dvandvasamāsa.
iṣa is a name/synonym of the month Āśvina;
ūrja is a name/synonym of the month Kārtika.

**Comment by drdhaval2785** [comment]
# Case 2
```
प्रोच्यन्ते प्राचिकाः श्येनाश्चटिकाः क्षुद्रपक्षिकाः ॥ २५३ ॥
```
What would be the parse ?
cawika / cawikA 
kzudrapakzika / kzudrapakzikA , @Harunaga-Isaacson ?

**Comment by drdhaval2785** [comment]
# Case 3
```
अध्वा पन्थाः पद्धतिरेकपदी वर्त्म वर्तनी सरणिः ।
```
पथ / पथस् / पथन् / पन्थ ? 
What is the prAtipadika here?

**Comment by drdhaval2785** [comment]
# Case 4
```
दाराः क्षेत्रं कलत्रं च भार्या सहचरी वधूः ।
सधर्मचारिणी पत्नी जाया च गृहिणी गृहाः ॥ ४९४ ॥
```
Last item is गृह / गृहा / गृहाः ? What is the synonym of wife in this context?

**Comment by vvasuki** [comment]
> # Case 3
> 
> ```
> अध्वा पन्थाः पद्धतिरेकपदी वर्त्म वर्तनी सरणिः ।
> ```
> 
> पथ / पथस् / पथन् / पन्थ ?
> What is the prAtipadika here?

पथिन्

**Comment by vvasuki** [comment]
> # Case 4
> 
> ```
> दाराः क्षेत्रं कलत्रं च भार्या सहचरी वधूः ।
> सधर्मचारिणी पत्नी जाया च गृहिणी गृहाः ॥ ४९४ ॥
> ```
> 
> Last item is गृह / गृहा / गृहाः ? What is the synonym of wife in this context?

गृहाः।

**Comment by drdhaval2785** [comment]
# Case 5
```
भृष्टा यवास्तु धाना दरपक्वा कथ्यतेऽभ्यूषः ॥ ५८५ ॥
```
What is this word दरपक्वा ?

**Comment by vvasuki** [comment]
> # Case 5
> 
> ```
> भृष्टा यवास्तु धाना दरपक्वा कथ्यतेऽभ्यूषः ॥ ५८५ ॥
> ```
> 
> What is this word दरपक्वा ?

=ईषत्पक्वा इति भाति

**Comment by vvasuki** [comment]
> # Case 2
> 
> ```
> प्रोच्यन्ते प्राचिकाः श्येनाश्चटिकाः क्षुद्रपक्षिकाः ॥ २५३ ॥
> ```
> 
> What would be the parse ?
> cawika / cawikA
> kzudrapakzika / kzudrapakzikA , @Harunaga-Isaacson ?

चटकजातेः स्त्रीश् चटिका भवेत्। स्त्रीलिङ्गत्वात् क्षुद्रपक्षिका इत्येव।

**Comment by drdhaval2785** [comment]
>‌ case 2.

So, I should treat चटिका क्षुद्रपक्षिका as headwords. Thanks @vvasuki .

**Comment by drdhaval2785** [comment]
> case 3

पथिन् seems right. Thanks

**Comment by drdhaval2785** [comment]
> Case 5

The following entry in Vachaspatyam about 'dara' confirms that it is for ईषद्
```
दर अव्य० दॄ—भये अप् । १ ईषदर्थे । २ भये, ३ गर्त्ते चपुंन० ।
अमरः “दरादराभ्यां दरकम्पिनी पपे” नैषधम्
“दरमीलन्नयनानिरीक्षते” रसगङ्गा० । “न जात-
हार्द्देन न विद्विषादाः” किरा० । ४ कन्दरे पुंस्त्री०
स्त्रीत्वे ङीप् । “दरीगृहोत्सङ्कनिषक्तभासः” । “दरीमुखो
त्वितेन समीरणेन” कुमा० । ५ शङ्खे शब्दार्थचि० । “स
उच्चकाशे धवलो दरोदरीप्युरुक्रमस्याधरशीणशीणि-
मेति” भाग० । [ID=24415]
```

**Comment by drdhaval2785** [comment]
# Case 6
```
#एध,तर्पण,इन्धन,एध,समिध्,इध्मन्
एधस्तर्पणमिन्धनमधः समिदिध्म इत्यभिन्नार्थाः ।
```
I am unable to parse अधः . Is there any word which can mean thus?
It can also be अघः . I am not sure. @Harunaga-Isaacson or @vvasuki may throw some light.

**Comment by drdhaval2785** [comment]
Case 6 may be treated as closed. It is एधस् . एध and एधस् are different words 
एध - इन्ध् + 'हलश्च' इति करणे घञ् ।
एधस् - एध् + असुन् 
According to page 187 of Explanations at the end of Halayudhakosha.
Mark of e is very faint in the scan. Noting it as print change.
