### ISSUE TITLE
Viśvalocanakośa typo

### ISSUE THREAD

**Issue by Harunaga-Isaacson** [sanskrit-kosha/kosha#50]
In the line 
नभश्चरो` धने विद्याधरे वाते विहङ्गमे ॥ २७९ ॥
we should, I suggest, have नभश्चरो घने .
(I do not have a PDF of the edition at hand to check whether this
as an error in OCR/input, or a printing error in the edition.)
With much appreciation of the wonderful resources for Sanskrit students
in this repository!
Harunaga Isaacson

**Comment by drdhaval2785** [comment]
![image](https://user-images.githubusercontent.com/5755132/152674622-aad63f46-bc69-49ca-a713-c8b2c1f4b154.png)
