### ISSUE TITLE
typo in Abhidhānacintāmaṇi 688

### ISSUE THREAD

**Issue by arlogriffiths** [sanskrit-kosha/kosha#51]
ālāvartaṃ tu vastrasya kaṅkataḥ keśamārjanam |
prasādhanaś cātha bālakrīḍanake guḍo giriḥ || 688 ||

Those are the romanized data from the e-text in this repo.

I suppose keśamārjanam is a typo for keśamārjanaḥ.

This edition shows the correct reading: http://archive.org/details/abhidhan_chintamani_002275_hr6.

<img width="217" alt="Capture d’écran 2024-03-13 à 13 59 47" src="https://github.com/sanskrit-kosha/kosha/assets/835603/7f5bb97c-c081-4d82-bb79-5aac0ba427ee">

**Comment by drdhaval2785** [comment]
In स्वोपज्ञवृत्ति and व्युत्पत्तिरत्नाकर, it is indeed shown as केशमार्जनः
Changing it.
The only issue is that it is a word known to take all three genders as per व्युत्पत्तिरत्नाकर commentary.
![Screenshot_2024-03-13_17-41-45](https://github.com/sanskrit-kosha/kosha/assets/5755132/50ecfb6c-8391-46fa-9e4a-2ca20378ff7d)

**Comment by drdhaval2785** [comment]
@arlogriffiths 
https://github.com/sanskrit-kosha/kosha/commit/0de158654e10b0aa1991f459af282d3ed77a725a may be of interest to you. A lot of corrections from my working file have been carried forward to Abhidhanachintamani files.

**Comment by arlogriffiths** [comment]
thanks a lot. I will download all files in their revised form.

best,

Arlo

Le 13 mars 2024 à 19:23, Dr. Dhaval Patel ***@***.******@***.***>> a écrit :



@arlogriffiths<https://github.com/arlogriffiths>
0de1586<https://github.com/sanskrit-kosha/kosha/commit/0de158654e10b0aa1991f459af282d3ed77a725a> may be of interest to you. A lot of corrections from my working file have been carried forward to Abhidhanachintamani files.
