### ISSUE TITLE
error in amaratikasarvasva

### ISSUE THREAD

**Issue by arlogriffiths** [sanskrit-kosha/kosha#52]
in the line 16554 `<s>abhyavaskandanaṃ tvabhyāsānaṃ</s>` the syllable da has been omitted, as it should be tvabhyāsādanaṃ.

cf. AK.02.08.110ab abhyavaskandanaṃ tvabhyāsādanaṃ vijayo jayaḥ |

I haven't taken the time to check if this is an error of the edition or the digitization process.

**Comment by drdhaval2785** [comment]
Corrected via above commit
