### ISSUE TITLE
अनेकार्थतिलक issues

### ISSUE THREAD

**Issue by Harunaga-Isaacson** [sanskrit-kosha/kosha#6]
1. उः क्रोधे बन्धने लोभे विभागेऽव्ययं गुरौ ॥ ७ ॥
The printed edition has as first word here not उः but उ, without visarga.
However I wonder if there is a printing mistake here. The previous
line teaches the meanings of  उ (उः being the prathamaanta-form meaning
'the word उ'). This line should perhaps be teaching the meanings of ऊ; we expect
then as first word ऊः. I would recommend trying to consult learned scholars, and if possible checking a manuscript or manuscripts of the अनेकार्थतिलक. 

2. और्धातर्यौरनन्ते  should certainly be corrected to ओर्धातर्यौरनन्ते, which
is what the printed edition in fact has. 

3. अर्घः पूजाविधी --> अर्घः पूजाविधौ (as in the printed edition).

With thanks and much appreciation for this as well as many other most valuable contributions, 

Harunaga Isaacson

**Comment by drdhaval2785** [comment]
It indeed is उ in printed edition. So changing it to उ .
