### ISSUE TITLE
Use another edition for Nighantushesha

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-kosha/kosha#9]
https://github.com/sanskrit-kosha/kosha/issues/7#issue-459588275 where @Harunaga-Isaacson suggested very important thing.

While filling in the missing data, it seemed that the Nirnayasagara edition is full of errors. As LD edition is with commentary, it is way way better.
It is worthwhile to make LD edition the base edition for Nighantushesha. 
This would take a lot of time though.
Keeping it here, so that it is not lost sight of.

**Comment by Harunaga-Isaacson** [comment]
That would indeed be excellent!

**Comment by gasyoun** [comment]
Why not have the list of planned dictionaries as we list in another issue?

**Comment by drdhaval2785** [comment]
@gasyoun https://github.com/sanskrit-kosha/kosha/issues/14 is the current status

**Comment by drdhaval2785** [comment]
Received physical copy of LD edition of nighantushesha. Will try to make necessary corrections based on this edition soon @Harunaga-Isaacson .

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-kosha/kosha/commit/4fe876e06b45c1c4f574698c454244b39fe8e96d made a major change. Now the edition used is LDII. For info to @Harunaga-Isaacson .
